# Data options
data_dir: offline_load_P
fourier_features: true
online: false
bootstrap: false

# Model/ensemble options
model_name: null
ensemble_size: 0
ensemble_name: null
model_type: ResOrthoONet

# Training hyperparameters
iterations: 40000
lr: 0.005
batch_size: 64
loss: mean l2 relative error

# Layer sizes
layers: [20, 20, 20, 20, 20, 20]

# Scheduler options
decay_gamma: 0.9998465  # 15k iterations
minimum_lr: 0.0005

# Reproducibility and Debugging
verbose: true
display_every: 1000