# Data options
data_dir: offline_voltage
fourier_features: true
online: false
bootstrap: false

# Model/ensemble options
model_name: null
ensemble_size: 0
ensemble_name: null
model_type: ResOrthoONet

# Training hyperparameters
iterations: 40000
lr: 0.0005
batch_size: 256
loss: MSE

# Layer sizes
layers: [20, 20, 20, 20, 20, 20]

# Scheduler options
decay_gamma: null
minimum_lr: null

# Reproducibility and Debugging
verbose: true
display_every: 1000